from beatrix.bundles.files import *
from beatrix.bundles.keystrokes import *
from beatrix.bundles.camera_capture import *
from beatrix.bundles.screen_capture import *
from beatrix.bundles.gmeet import *
from beatrix.bundles.zoom import *
from beatrix.bundles.duckduckgo import *
from beatrix.bundles.power import *
from beatrix.bundles.browser import *
from beatrix.bundles.volume import *
from beatrix.bundles.torrent import *
